# This file contains values from Cookiecutter

default_context:
  project_name: "notifications-admin"
  package_name: "notifications_admin"
  git_platform: "github"
  username: "a1d4r"
  git_repo_url: "https://github.com/a1d4r/practicum-notifications"
  python_version: "3.12"
  line_length: "100"
