# Generated by Django 4.2.5 on 2024-08-08 10:13

from django.db import migrations, models
import django.db.models.deletion
import notifications.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                         CREATE SCHEMA notification
                     """,
            reverse_sql='DROP SCHEMA notification',
        ),
        migrations.CreateModel(
            name='NotificationsContents',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255, verbose_name='event type')),
                ('template_variables', models.JSONField(verbose_name='Template Variables')),
                ('user_id', models.UUIDField(verbose_name='User ID')),
                ('user_group_id', models.UUIDField(verbose_name='Group ID')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'notification"."notification_contents',
            },
        ),
        migrations.CreateModel(
            name='NotificationsTemplates',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255, verbose_name='event type')),
                ('template_text', models.TextField(validators=[notifications.models.jinja_validator], verbose_name='Template')),
                ('channels', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('websocket', 'WebSocket')], max_length=255, verbose_name='channels')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'notification"."notification_templates',
                'indexes': [models.Index(fields=['event_type'], name='event_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(auto_now=True, verbose_name='last sent at')),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationscontents', verbose_name='content id')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification"."notifications',
            },
        ),
    ]
