services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./notifications_worker:/app/notifications_worker

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
